### ISSUE TITLE
Preserving orientation information

### ISSUE THREAD

**Issue by williamhaley** [koofr/epeg#2]
Thanks for your work on this and https://github.com/koofr/goepeg! Incredibly fast solutions with a nice simple API.

I saw in #1 that this and the upstream diverged a bit, but one behavior that may be worth porting over is... https://github.com/mattes/epeg/commit/126c514f2d53a8a47a26961901071abf15443e3d

If I compile https://github.com/mattes/epeg from source and run the binary against an image it preserves orientation, but https://github.com/koofr/epeg.git seems to miss out on that functionality. 

I'm not sure how to build this fork's `epeg` as a standalone binary, but I can at least use the https://github.com/koofr/goepeg library with bindings to validate that it's not preserving rotation.

```
package main

import (
	"github.com/koofr/goepeg"
	"log"
	"os"
	"strconv"
)

func main() {
	args := os.Args[1:]

	dimension, err := strconv.Atoi(args[2])
	if err != nil {
		log.Fatal(err)
	}

	quality := 100
	if err := goepeg.Thumbnail(args[0], args[1], dimension, quality, goepeg.ScaleTypeFitMax); err != nil {
		log.Fatal(err)
	}
}
```

The upstream `epeg` preserves orientation data.

<img width="253" alt="Screen Shot 2020-11-19 at 11 07 47 PM" src="https://user-images.githubusercontent.com/1851748/99761648-3832be80-2abc-11eb-8624-f2684351451b.png">

But this fork loses that unfortunately.

<img width="157" alt="Screen Shot 2020-11-19 at 11 08 00 PM" src="https://user-images.githubusercontent.com/1851748/99761660-3e289f80-2abc-11eb-8048-b87d643a37ec.png">

I'm happy to help if I can, but I imagine I don't know enough about the implementation or C in general to be of much assistance.

**Comment by bancek** [comment]
We don't use epeg directly and handle the rotation manually.

We have another library https://github.com/koofr/gothumb/blob/master/thumbnail.go that handles that so that we have more control over transformations.

**Comment by williamhaley** [comment]
Just what I needed. Thanks!
